### ISSUE TITLE
404s not being added to errors array

### ISSUE THREAD

**Issue by smillerk2** [seethroughtrees/casperjs-spider#7]
The spider works well but I'm finding that 404s from the same domain are not being added to the errors array. Is this by design or an issue? Is it possible to add an errorCount property such that consumers of the JSON know if there are issues with the crawl (rather than traversing the entire links collection)?

```javascript
{
  "start": "http://test.xxx.com",
  "date": "2015-03-02T18:35:48.946Z",
  "dateFileName": true,
  "requiredValues": [
    "test.xxx.com"
  ],
  "skippedValues": [
    "default"
  ],
  "links": [
    {
      "url": "http://test.xxx.com#portfolioModal6",
      "status": 200
    },
    {
      "url": "http://test.xxx.com#",
      "status": 200
    },
    {
      "url": "http://test.xxx.com/help",
      "status": 404
    },
    {
      "url": "http://test.xxx.com/contact",
      "status": 404
    }
  ],
  "errors": [],
  "messages": [],
  "skippedLinksCount": 7,
  "logFile": "./logs/2015-03-02-data.json",
  "linkCount": 4,
  "userAgent": null
}
```

**Comment by seethroughtrees** [comment]
That does sound weird.  Its been a while since I've been in this code.  I'll try and take a look tomorrow, let you know what I find.  And sure, an errorCount would be no problem.

**Comment by seethroughtrees** [comment]
Okay, I just went through it.

The errors array is only for catching javascript errors.  And it does appear to work as expected.  

As a 404 wouldn't be considered an error, its not included.  

You could easily filter the errors from the links array.  with Array.filter() and get your own list though.  
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

Let me know if that works, or if you get stuck.

**Comment by smillerk2** [comment]
Thanks for your quick response - greatly appreciated. Here is the issue. One of the pages being crawled contains inline invalid JavaScript:

```
<script type="text/javascript">
	var x=;
</script>
```
This correctly shows in the console in Chrome as an error (as expected):
```
Uncaught SyntaxError: Unexpected token ;
```

However, the spider doesn't seem to find this. The errors[] and messages[] arrays are both empty in the resulting JSON log file. Can you give an example showing how you got this to work and be reported on?

What I'd like to do is tie your spider library with a continuous integration system and have sites immediately crawled post build to detect client side JavaScript errors. I can then parse the JSON file and report on the errors in Jenkins. Great library!

**Comment by seethroughtrees** [comment]
Sounds like a cool use.  I have integrated this with something similar, and its being used internally on a pretty large site.  

I ran the script for the first 10000 pages of a site I work on was able to see errors and warnings. Don't know if it helps, but here you go:  (I obfuscated the actual site url)

```
"errors": [
    {
      "msg": "TypeError: 'undefined' is not an object (evaluating '$.getJSON')",
      "file": "http://www.site.com/scripts/account/creation/dynamic.0162.js",
      "line": 31,
      "func": ""
    },
    {
      "msg": "TypeError: 'undefined' is not an object (evaluating '$.getJSON')",
      "file": "http://www.site.com/scripts/account/creation/dynamic.0162.js",
      "line": 31,
      "func": ""
    },
    {
      "msg": "TypeError: 'undefined' is not a function (evaluating '$(window).width()')",
      "file": "http://www.site.com/scripts/landing/dynamic.0162.js",
      "line": 16,
      "func": ""
    },
    {
      "msg": "TypeError: 'null' is not an object (evaluating '$('html').removeClass')",
      "file": "http://www.site.com/gallery/",
      "line": 360,
      "func": ""
    }
  ],
  "messages": [
    {
      "url": "http://www.site.com/",
      "msg": "Viewport argument key \"minimal-ui\" not recognized and ignored."
    },
    {
      "url": "http://www.site.com/",
      "msg": "Viewport argument key \"minimal-ui\" not recognized and ignored."
    },
    {
      "url": "http://www.site.com/examples/",
      "msg": "BrightTag: error: {\"type\":\"script\",\"message\":\"Problem loading //s.thebrighttag.com/\",\"tagId\":-2}"
    },
    {
      "url": "http://www.site.com/#",
      "msg": "Viewport argument key \"minimal-ui\" not recognized and ignored."
    },
```
