### ISSUE TITLE
load-images parameter not working

### ISSUE THREAD

**Issue by smillerk2** [seethroughtrees/casperjs-spider#8]
The load-images parameter doesn't seem to be working from the command line:

```javascript
$ casperjs.exe --start-url=http://test.xxx.com --required-values=test.xxx.com --load-images=true spider.js
```
Even if I change this within config.js explictly the spider doesn't seem to crawl <img> tags in my site's pages.

Version: 1.1.0-beta3 and 1.9.6 for phantomjs.

**Comment by seethroughtrees** [comment]
Hmm.  Can you be more specific?  The images shouldn't affect any crawling.  If any hrefs are wrapped, they will still follow.

I only added that option in case someone modified to get screenshots, if I remember correctly...

**Comment by smillerk2** [comment]
Sure. I had set --load-images=true in the hope that the crawler would actually validate the existence (or lack thereof) of images contained within the pages being crawled. So, if I have this mark up in one of my pages:

```
<img src="img/blah.jpg"/>
```
This image is missing from the web server but is not being reported as such in the generated JSON log file.

Have I misinterpreted the way this feature works?

**Comment by seethroughtrees** [comment]
Ahh, yeah.  Sorry.  The crawler is only tracking the initial network request of each page.  So you're basically hitting the page, searching for links, and hitting those pages.  not actually hitting each asset.  

Although you could definitely modify the code to do that.  Around line 111, you would want to push all local asset urls, not just the hrefs.
