### ISSUE TITLE
is there a way to store page content in filesystem or mongodb

### ISSUE THREAD

**Issue by onurakman** [seethroughtrees/casperjs-spider#9]
is there a way to store page content in filesystem or mongodb for parsing page contents after crawling finishes

**Comment by seethroughtrees** [comment]
For now, you could modify spider.js :225.  And change the fs function to whatever you want to do with the data obj.  

When I get a chance I'll put a callback in there though so you could have access from the config file.

**Comment by seethroughtrees** [comment]
It was pretty quick, so i just exposed a callback to the config file.  You can now add or uncomment:

```config.cb = function(data) {return data;}```

And do anything you want with the data object.

Commit:  https://github.com/seethroughtrees/casperjs-spider/commit/fb19c4b471e63df3fa642bbc6400294d38b1572e
